# This is the configuration used to check the rubocop source code.

require:
  - rubocop-performance
  - rubocop-rails

AllCops:
  NewCops: enable
  
Style/StringLiterals:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false

Metrics/MethodLength:
  Max: 30

Metrics/AbcSize:
  Max: 25

Layout/LineLength:
  Max: 175